### ISSUE TITLE
Error "seed value is too big [for an uint]" when generating a new tile

### ISSUE THREAD

**Issue by lgommans** [iZlovreD/ZAdventure#1]
I tried the mod with two save games, but in both I get the following error as soon as I ran far enough that a new chunk is to be generated. No other mods active, latest game version.

    363.491 Error MainLoop.cpp:1035: Exception at tick 18956891: Error while running event ZAdventure::on_chunk_generated (ID 12)
    Given seed value (34225932140) is too big, the data type allows values from 0 to 4294967295
    stack traceback:
	__ZAdventure__/control.lua:134: in function 'Rnd'
	__ZAdventure__/control.lua:201: in function 'GetRandomArea'
	__ZAdventure__/control.lua:902: in function <__ZAdventure__/control.lua:867>

**Comment by iZlovreD** [comment]
Will be fixed in 1.1.8

**Comment by iZlovreD** [comment]
Updated.
