### ISSUE TITLE
Error while loading Mods

### ISSUE THREAD

**Issue by hasezoey** [iZlovreD/ZAdventure#2]
Error while loading font prototype "zadv_lable_race_font_1" (font): File: \_\_ZAdventure\_\_/locale/digital.tff not found
Modifications: [Z] Adventure

just updated the mod

EDIT: mistyped something above here, fixed in a later post

**Comment by iZlovreD** [comment]
Hm.. weird. Font file extension is .ttf and it is in place. And prototype uses .ttf file.
Unzip mod and check it, please.

**Comment by hasezoey** [comment]
it is there but it is named `digital.ttf` and not `digital.tff` (notice the tff & ttf difference)

**Comment by iZlovreD** [comment]
Yeah. It should be .ttf. Check info.json file in /locale/en folder

**Comment by hasezoey** [comment]
```json
{
  "language-name": "English",
  "font": {
    "zadv-race-timer": 
    [
      "__ZAdventure__/locale/digital.ttf"
    ]
  }
}
```

**Comment by iZlovreD** [comment]
Hm... gimme a few mins. i've got one idea why it may happens.

**Comment by iZlovreD** [comment]
steam version?

**Comment by hasezoey** [comment]
steam version.

**Comment by iZlovreD** [comment]
I'm sorry, i want to ask which one? 0.16.51?

**Comment by hasezoey** [comment]
idk, just wrote above ...
0.16.51

**Comment by hasezoey** [comment]
Factorio Version: 0.16.51
Mod Version: 1.16.0
Windows (10) latest
Steam beta update (latest)

**Comment by iZlovreD** [comment]
I'm just trying to reproduce your error...

**Comment by hasezoey** [comment]
i fixed it:
rename in the info.json `/digital.ttf` with `/digital.TTF` or just rename the file to lower case, and all things work

**Comment by iZlovreD** [comment]
Yea, did the same about 1 min ago, and almost asking to try it ))

**Comment by iZlovreD** [comment]
Let's count it is fixed.
