### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by hasezoey** [iZlovreD/ZAdventure#3]
is it right to think the mod works by placing a chest with a blueprint and then generating the structure?
when yes, i get only the chest with blueprints, and no structures

Factorio: 0.16.51 (Steam)
Windows 10
Mod Version: 1.16.1
when you want some images, i could provide

Mods Chaning Genrating:
(Noxys Trees?)
Oreverhaul

Update: just found one generated structure, but still generating mostly only chests with blueprints

**Comment by iZlovreD** [comment]
Check "Types or areas" spoiler here: https://forums.factorio.com/viewtopic.php?p=371945#p371945
What kind of area/structure is random and depends on probability of each.
Also you can play with mod settings to increase or lower chances.

Anyway it is a question of balancing - how often and how many.

**Comment by iZlovreD** [comment]
It is such type of area - chest with random blueprint in it.
Also, as i wrote earlier, you can unckeck unwanted areas in settings.

And yes, some structures cannot be mined or damaged.

**Comment by hasezoey** [comment]
thanks for the clarification.

this `And yes, some structures cannot be mined or damaged.`  can this be changed too?

**Comment by iZlovreD** [comment]
Nope. =)
This is how it was conceived to save area integrity.
But almost all areas of what you can find can be removed someway (mined, damaged or somehow else)

**Comment by hasezoey** [comment]
Thanks ^^
