### ISSUE TITLE
Game Startup Error

### ISSUE THREAD

**Issue by hasezoey** [iZlovreD/ZAdventure#4]
![](https://i.imgur.com/J3c2c7y.png)
Hi Again.

Factorio: 0.16.51
Mod V: 1.16.2

**Comment by iZlovreD** [comment]
Looks like some other mod change flamethrower ammo...
I'll make it independable.

**Comment by hasezoey** [comment]
I use all 5 Dims mods can it be 5Dim - battlefield? or AAI Flamethrower (i think not)

**Comment by iZlovreD** [comment]
Updated.

**Comment by hasezoey** [comment]
nope, it is still here, nothing has changed

**Comment by hasezoey** [comment]
got it fixed when in `data-updates.lua`  changing (firstly removing the space) and then replace `.ammo_type[1]` with `.ammo_type`

**Comment by iZlovreD** [comment]
can you share your mod-list.json from mod folder?
(pastebin)

**Comment by hasezoey** [comment]
https://gist.github.com/hasezoey/bf04abb4c5a2e7e0368642122080e99b
all mods, using my own converter (removing the disabled ones and removing the json)

**Comment by iZlovreD** [comment]
"replace .ammo_type[1] with .ammo_type"
It's workaround, not a fix =)

**Comment by hasezoey** [comment]
sorry i dont really know lua, but it fixed it for me

**Comment by iZlovreD** [comment]
yep

**Comment by iZlovreD** [comment]
And yes, it was because of AAI flame tank mod, witch rewrite vanila content.

**Comment by hasezoey** [comment]
didnt know that.
can confirm that it works again ^^
